### ISSUE TITLE
State of the Project: Challenges and Call for Support

### ISSUE THREAD

**Issue by alexchopstix** [UnstoppableSwap/unstoppableswap-gui#199] opened 2024-05-20 21:39 UTC
I see nothing but people having issues with this app, I feel like it was released for main net use a little too early. Clearly needs more development, and there hasn't been a newly released version in 6 months. I don't know just doesn't seem like something that's even worth using unless your using the testnet.

**Comment by alexchopstix** [comment] 2024-05-22 00:53
Nevermind I'm closing this, it seems like this project has pretty much been abandoned, no one as even posted an issue or question in over a month. Sad really seems like it had potential.

**Comment by binarybaron** [comment] 2024-05-22 11:28
I know there are issues with UnstoppableSwap, and it honestly makes me sad that I haven't been able to give this project the time and attention it deserves. It's just me working on this at the moment, and I simply don't have the resources to dedicate to it that it needs and deserves.

I started this project purely out of my own passion for Monero and Atomic Swaps. I truly believe in the potential of decentralized technologies and want to see them put into practice. I've been spending my own money to fund this project and bring this vision to life, such as by offering [bounties on the upstream project](https://github.com/comit-network/xmr-btc-swap/issues?q=is%3Aopen+is%3Aissue+label%3A%22Bounty+%F0%9F%92%B0%22). But building something this intricate is tough. There are a ton of moving parts, and keeping it all together working in sync flawlessly is difficult, to say the least.

I hope that I will be able to spend more time on this soon and fix the few but serious issues troubling this project. I see the potential, and it makes me sad as well that I haven't been able to fully realize it. This project is so close to being stable, but I simply lack the resources currently to get it across the finish line. 95% of the work has been done; we're just missing the last few miles.

Most of the issues are not caused by this project itself (the GUI) but rather the underlying [project](https://github.com/comit-network/xmr-btc-swap) that is used to handle the swaps, network requests, cryptography, and more. I have been driving an effort to improve the issues in that project as well by making Pull Requests and funding GitHub issues with bounties, but we're simply lacking the manpower.

Despite these challenges, I remain committed to the project and the vision of making atomic swaps more accessible. I appreciate the community's patience and understanding. If anyone is interested in contributing their skills or resources to help push UnstoppableSwap forward, please don't hesitate to reach out. Together, I believe we can make this project a success. I'm not giving up.

**Comment by binarybaron** [comment] 2024-05-22 11:52
I've been working on a huge rework of the entire structure of the whole project and once this https://github.com/comit-network/xmr-btc-swap/pull/1276 PR gets merged in the underlying project we'll be able to move forward with it.

**Closed** 2024-06-28 15:18 UTC
Labels: question
